### ISSUE TITLE
README

### ISSUE THREAD

**Issue by shalom2552** [malul88/atam_hw1#1]
Missing 'README.md' file at "malul88/atam_hw1"

**Comment by malul88** [comment]
Hi

Updated the README file on GitHub you can check it and give some feedback as well.






***@***.***D59411.34308E90]

מאת: ***@***.***>
נשלח: שבת 24 אפריל 2021 13:17
אל: ***@***.***>
עותק: ***@***.***>
נושא: [malul88/atam_hw1] README (#1)


Missing 'README.md' file at "malul88/atam_hw1"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmalul88%2Fatam_hw1%2Fissues%2F1&data=04%7C01%7Cmichaelmalul%40campus.technion.ac.il%7C5eb77f374495492b2fb508d9070a39a3%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637548562789779546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uRYPjwKdBCR1%2FV9hb6oBsSWQ7H5CVhrE%2FCJ%2BeUpaKfQ%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO73DJXILORIY4224UB4G6DTKKLFDANCNFSM43P74GXA&data=04%7C01%7Cmichaelmalul%40campus.technion.ac.il%7C5eb77f374495492b2fb508d9070a39a3%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637548562789779546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qOKq7caIZ%2FMMJ2P6UGamxFkC8pVGgFYD14Oa2Il%2FF1M%3D&reserved=0>.

External e-mail, be judicious when opening attachments or links

**Comment by shalom2552** [comment]
Very well!
Looks superb! 
You can close this issue
